apiVersion: v1
kind: Service  # to expose the port 
metadata:
  name: jenkins
  namespace: default
spec:
  type: ClusterIp
  ports:
  - name: httpport
    port: 8080
    targetPort: 8080
  - name: jnlpport
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
